name: Run Unit Tests

on: push
jobs:
  run-tests:
    runs-on: python:3.10.12
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install django
        run: pip3 install django==5.1.7
      - name: Install django REST framework
        run: pip3 install djangorestframework==3.15.2
      - name: Run unit tests
        run: python3 manage.py test todo
        