# Generated by Django 5.1.7 on 2025-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
