# Generated by Django 5.1.7 on 2025-03-27 04:53

import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_name_todo_title_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('H', todo.models.TodoPriority['HIGH']), ('M', todo.models.TodoPriority['MEDIUM']), ('L', todo.models.TodoPriority['LOW'])], default='M', max_length=1),
        ),
    ]
