name: Run Unit Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtualenv
        run: python3 -m venv env
      - name: Initialize venv
        run: source env/bin/activate
      - name: Install django
        run: pip3 install django==5.1.7
      - name: Install django REST framework
        run: pip3 install djangorestframework==3.15.2
      - name: Install cors headers
        run: pip3 install django-cors-headers==4.7.0
      - name: Run unit tests
        run: python3 todo_list/manage.py test todo
        